/*
 * generated by Xtext
 */
package jp.toppers.tecs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CdlRuntimeModule extends jp.toppers.tecs.AbstractCdlRuntimeModule {

}
