/*
 * generated by Xtext
 */
package jp.toppers.tecs;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CdlStandaloneSetup extends CdlStandaloneSetupGenerated{

	public static void doSetup() {
		new CdlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

