/*
 * generated by Xtext
 */
package jp.toppers.tecs.ui.contentassist

import jp.toppers.tecs.ui.contentassist.AbstractCdlProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CdlProposalProvider extends AbstractCdlProposalProvider {
}
