/*
 * generated by Xtext
 */
package jp.toppers.tecs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CdlUiModule extends jp.toppers.tecs.ui.AbstractCdlUiModule {
	public CdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
